cucumber:
   reanmigrate:
       automation:
         authentication:
            admin_password: "${admin_password:admin}"
            admin_user: "${admin_user:admin}"
            ssh_key: "${SSHKEY:}"
     
         common:
            browser: "${BROWSER:Chrome}"
            platform_url: "${URL:http://prod-bmw-alb-1225467072.ap-northeast-1.elb.amazonaws.com:9000/mi-dashboard}"        
    